export const LIST_BOARD_SUCCESS = 'LIST_BOARD_SUCCESS';
export const SELECT_BOARD = 'SELECT_BOARD';
export const CLEAR_BOARD = 'CLEAR_BOARD';

export const LIST_CARD_SUCCESS = 'LIST_CARD_SUCCESS';
export const SELECT_CARD = 'SELECT_CARD';
export const CLEAR_CARD = 'CLEAR_CARD';

export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING';

export const LIST_ENTRY_SUCCESS = 'LIST_ENTRY_SUCCESS';
export const CLEAR_ENTRIES = 'CLEAR_ENTRIES';

export const LIST_INVOICE_SUCCESS = 'LIST_INVOICE_SUCCESS';
export const CLEAR_INVOICES = 'CLEAR_INVOICES';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_API_KEY = 'SET_API_KEY';

// messages
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
